packages:
  - "packages/*"

allowBuilds:
  esbuild: false
  lefthook: true

autoInstallPeers: true
injectWorkspacePackages: true
publicHoistPattern:
  - "*@biomejs/biome*"
  - "*@e18e/cli*"
  - "*@total-typescript/tsconfig*"
  - "*lefthook*"

minimumReleaseAgeExclude:
  - "idleberg/configs"
  - "@nsis/dent"
  - "@idleberg/configs@0.4.4"

catalog:
  vite: ^8.0.16
  vitest: ^4.1.8
