import { completeFromList } from '@codemirror/autocomplete';
import { foldInside, foldNodeProp, indentNodeProp, LanguageSupport, LRLanguage } from '@codemirror/language';
import { nsisHighlighting } from './highlight';
import { parser } from './parser';

export const nsisLanguage = LRLanguage.define({
	name: 'nsis',
	parser: parser.configure({
		props: [
			nsisHighlighting,
			indentNodeProp.add({
				FunctionBlock: (cx) => cx.baseIndent + cx.unit,
				SectionBlock: (cx) => cx.baseIndent + cx.unit,
				SectionGroupBlock: (cx) => cx.baseIndent + cx.unit,
				PageExBlock: (cx) => cx.baseIndent + cx.unit,
				MacroBlock: (cx) => cx.baseIndent + cx.unit,
				PreprocConditional: (cx) => cx.baseIndent + cx.unit,
			}),
			foldNodeProp.add({
				FunctionBlock: foldInside,
				SectionBlock: foldInside,
				SectionGroupBlock: foldInside,
				PageExBlock: foldInside,
				MacroBlock: foldInside,
				PreprocConditional: foldInside,
				BlockComment: foldInside,
			}),
		],
	}),
	languageData: {
		commentTokens: { line: '#', block: { open: '/*', close: '*/' } },
		closeBrackets: { brackets: ['(', '[', '{', '"', "'", '`'] },
	},
});

const commands = [
	'Abort',
	'AddBrandingImage',
	'AddSize',
	'AllowRootDirInstall',
	'AllowSkipFiles',
	'AutoCloseWindow',
	'BGFont',
	'BGGradient',
	'BrandingText',
	'BringToFront',
	'Call',
	'CallInstDLL',
	'Caption',
	'ChangeUI',
	'CheckBitmap',
	'ClearErrors',
	'CompletedText',
	'ComponentText',
	'CopyFiles',
	'CPU',
	'CRCCheck',
	'CreateDirectory',
	'CreateFont',
	'CreateShortCut',
	'Delete',
	'DeleteINISec',
	'DeleteINIStr',
	'DeleteRegKey',
	'DeleteRegValue',
	'DetailPrint',
	'DetailsButtonText',
	'DirText',
	'DirVar',
	'DirVerify',
	'EnableWindow',
	'EnumRegKey',
	'EnumRegValue',
	'Exch',
	'Exec',
	'ExecShell',
	'ExecShellWait',
	'ExecWait',
	'ExpandEnvStrings',
	'File',
	'FileBufSize',
	'FileClose',
	'FileErrorText',
	'FileOpen',
	'FileRead',
	'FileReadByte',
	'FileReadUTF16LE',
	'FileReadWord',
	'FileSeek',
	'FileWrite',
	'FileWriteByte',
	'FileWriteUTF16LE',
	'FileWriteWord',
	'FindClose',
	'FindFirst',
	'FindNext',
	'FindWindow',
	'FlushINI',
	'Function',
	'FunctionEnd',
	'GetCurInstType',
	'GetCurrentAddress',
	'GetDlgItem',
	'GetDLLVersion',
	'GetDLLVersionLocal',
	'GetErrorLevel',
	'GetFileTime',
	'GetFileTimeLocal',
	'GetFullPathName',
	'GetFunctionAddress',
	'GetInstDirError',
	'GetKnownFolderPath',
	'GetLabelAddress',
	'GetRegView',
	'GetShellVarContext',
	'GetTempFileName',
	'GetWinVer',
	'Goto',
	'HideWindow',
	'Icon',
	'IfAbort',
	'IfAltRegView',
	'IfErrors',
	'IfFileExists',
	'IfRebootFlag',
	'IfRtlLanguage',
	'IfShellVarContextAll',
	'IfSilent',
	'InitPluginsDir',
	'InstallButtonText',
	'InstallColors',
	'InstallDir',
	'InstallDirRegKey',
	'InstProgressFlags',
	'InstType',
	'InstTypeGetText',
	'InstTypeSetText',
	'Int64Cmp',
	'Int64CmpU',
	'Int64Fmt',
	'IntCmp',
	'IntCmpU',
	'IntFmt',
	'IntOp',
	'IntPtrCmp',
	'IntPtrCmpU',
	'IntPtrOp',
	'IsWindow',
	'LangString',
	'LicenseBkColor',
	'LicenseData',
	'LicenseForceSelection',
	'LicenseLangString',
	'LicenseText',
	'LoadAndSetImage',
	'LoadLanguageFile',
	'LockWindow',
	'LogSet',
	'LogText',
	'ManifestAppendCustomString',
	'ManifestDisableWindowFiltering',
	'ManifestDPIAware',
	'ManifestDPIAwareness',
	'ManifestGdiScaling',
	'ManifestLongPathAware',
	'ManifestMaxVersionTested',
	'ManifestSupportedOS',
	'MessageBox',
	'MiscButtonText',
	'Name',
	'Nop',
	'OutFile',
	'Page',
	'PageCallbacks',
	'PageEx',
	'PageExEnd',
	'PEAddResource',
	'PEDllCharacteristics',
	'PERemoveResource',
	'PESubsysVer',
	'Pop',
	'Push',
	'Quit',
	'ReadEnvStr',
	'ReadINIStr',
	'ReadMemory',
	'ReadRegDWORD',
	'ReadRegStr',
	'Reboot',
	'RegDLL',
	'Rename',
	'RequestExecutionLevel',
	'ReserveFile',
	'Return',
	'RMDir',
	'SearchPath',
	'Section',
	'SectionEnd',
	'SectionGroup',
	'SectionGroupEnd',
	'SectionGetFlags',
	'SectionGetInstTypes',
	'SectionGetSize',
	'SectionGetText',
	'SectionIn',
	'SectionInstType',
	'SectionSetFlags',
	'SectionSetInstTypes',
	'SectionSetSize',
	'SectionSetText',
	'SendMessage',
	'SetAutoClose',
	'SetBrandingImage',
	'SetCompress',
	'SetCompressionLevel',
	'SetCompressor',
	'SetCompressorDictSize',
	'SetCtlColors',
	'SetCurInstType',
	'SetDatablockOptimize',
	'SetDateSave',
	'SetDetailsPrint',
	'SetDetailsView',
	'SetErrorLevel',
	'SetErrors',
	'SetFileAttributes',
	'SetFont',
	'SetOutPath',
	'SetOverwrite',
	'SetRebootFlag',
	'SetRegView',
	'SetShellVarContext',
	'SetSilent',
	'ShowInstDetails',
	'ShowUninstDetails',
	'ShowWindow',
	'SilentInstall',
	'SilentUnInstall',
	'Sleep',
	'SpaceTexts',
	'StrCmp',
	'StrCmpS',
	'StrCpy',
	'StrLen',
	'SubCaption',
	'Target',
	'Unicode',
	'UnsafeStrCpy',
	'UninstallButtonText',
	'UninstallCaption',
	'UninstallIcon',
	'UninstallSubCaption',
	'UninstallText',
	'UninstPage',
	'UnRegDLL',
	'Var',
	'VIAddVersionKey',
	'VIFileVersion',
	'VIProductVersion',
	'WindowIcon',
	'WriteINIStr',
	'WriteRegBin',
	'WriteRegDWORD',
	'WriteRegExpandStr',
	'WriteRegMultiStr',
	'WriteRegNone',
	'WriteRegStr',
	'WriteUninstaller',
	'XPStyle',
];

const preprocDirectives = [
	'!addincludedir',
	'!addplugindir',
	'!appendfile',
	'!appendmemfile',
	'!assert',
	'!cd',
	'!define',
	'!delfile',
	'!echo',
	'!else',
	'!endif',
	'!error',
	'!execute',
	'!finalize',
	'!getdllversion',
	'!gettlbversion',
	'!if',
	'!ifdef',
	'!ifndef',
	'!ifmacrodef',
	'!ifmacrondef',
	'!include',
	'!insertmacro',
	'!macro',
	'!macroend',
	'!macroundef',
	'!makensis',
	'!packhdr',
	'!pragma',
	'!searchparse',
	'!searchreplace',
	'!system',
	'!tempfile',
	'!undef',
	'!uninstfinalize',
	'!verbose',
	'!warning',
];

const nsisCompletion = completeFromList(
	commands
		.map((c) => ({ label: c, type: 'keyword' }))
		.concat(preprocDirectives.map((d) => ({ label: d, type: 'keyword' }))),
);

export function nsis() {
	return new LanguageSupport(nsisLanguage, [nsisLanguage.data.of({ autocomplete: nsisCompletion })]);
}
